artifacts_root: artifacts


data ingestion: 
  root_dir: artifacts/data_ingestion
  source_URL: url = "https://drive.google.com/file/d/15SQdQy-TkE4A68e-hLX_4WOtzsOU7dMw/view?usp=sharing"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion